// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API支持",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/books": {
            "get": {
                "description": "获取所有图书\n获取所有图书信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图书管理"
                ],
                "responses": {
                    "200": {
                        "description": "图书列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Book"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "添加新书\n添加一本新书到图书库",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图书管理"
                ],
                "responses": {
                    "201": {
                        "description": "成功添加图书",
                        "schema": {
                            "$ref": "#/definitions/main.Book"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "409": {
                        "description": "图书ID已存在",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/books/{id}": {
            "get": {
                "description": "获取\n根据ID获取图书",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图书管理"
                ],
                "responses": {
                    "201": {
                        "description": "成功获取图书",
                        "schema": {
                            "$ref": "#/definitions/main.Book"
                        }
                    },
                    "404": {
                        "description": "为找到对应图书",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "description": "更新图书\n根据ID更新对应图书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图书管理"
                ],
                "responses": {
                    "200": {
                        "description": "成功更新图书",
                        "schema": {
                            "$ref": "#/definitions/main.Book"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "未找到对应图书",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除图书\n根据id删除图书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图书管理"
                ],
                "responses": {
                    "200": {
                        "description": "成功删除图书",
                        "schema": {
                            "$ref": "#/definitions/main.Book"
                        }
                    },
                    "404": {
                        "description": "未找到对应图书",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Book": {
            "description": "图书信息",
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "stock": {
                    "description": "修改为int类型更合理",
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "图书管理API",
	Description:      "这是一个简单的图书管理系统API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
